[project]
name = "algorithm-complexity-analysis"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "pandas>=2.2.3",
    "xlsxwriter>=3.2.3",
]

[dependency-groups]
dev = [
    "ipykernel>=6.29.5",
]
